runtime: python39
entrypoint: streamlit run app.py --server.port $PORT
instance_class: F2

env_variables:
  STREAMLIT_SERVER_PORT: $PORT
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"
  STREAMLIT_THEME_BASE: "dark"
  STREAMLIT_SERVER_MAX_UPLOAD_SIZE: "200"
  STREAMLIT_SERVER_ENABLE_CORS: "false"
  STREAMLIT_BROWSER_SERVER_ADDRESS: "0.0.0.0"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6
  max_concurrent_requests: 80
  min_pending_latency: 30ms
  max_pending_latency: automatic

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

network:
  session_affinity: true

readiness_check:
  app_start_timeout_sec: 300
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

inbound_services:
- warmup